### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by NiceCraftz** [Electroid/SportPaper#103]
Hello guys, I am kinda new to compiling ( I'm used to just downloading the jar from the site ) and I would like to know how to actually compile the server jar, I've installed maven on my machine, already had git, ran the command ./sportpaper build and encountered some errors.

Here is the link of the whole log https://paste.gg/p/anonymous/1e984be629364500aea528e86cabeabf

**Comment by VytskaLT** [comment]
Which Java version are you using? Pretty sure you can only build on JDK 8

**Comment by NiceCraftz** [comment]
> Which Java version are you using? Pretty sure you can only build on JDK 8

I am using java 8.

**Comment by VytskaLT** [comment]
Are you using Git bash? If not, try it and if it still doesn't work then try using [WSL](https://docs.microsoft.com/en-us/windows/wsl/install)
(I'm assuming you're on Windows)

**Comment by NiceCraftz** [comment]
> Are you using Git bash? If not, try it and if it still doesn't work then try using WSL (Windows Subsystem for Linux) (I'm assuming you're on Windows)

yes, i am using git bash, also sadly i can't mount WSL on my system.

**Comment by VytskaLT** [comment]
> > Are you using Git bash? If not, try it and if it still doesn't work then try using WSL (Windows Subsystem for Linux) (I'm assuming you're on Windows)
> 
> yes, i am using git bash, also sadly i can't mount WSL on my system.

I don't have any more ideas other than to check if you're on a JDK instead of a JRE

**Comment by NiceCraftz** [comment]
I was on a jdk

Il mer 10 nov 2021, 12:04 VytskaLT ***@***.***> ha scritto:

**Comment by zNoah-1** [comment]
I had a similar issue and managed to fix it by deleting "SportPaper/base/Paper/work/1.8.8/1.8.8-cl.jar"

What happened to me was that I initially ran the script on java 16, failed and moved to java 8, the previous attempt left an almost empty file rather than a 8.7mb file and that threw the ZipException.

**Comment by VytskaLT** [comment]
> I had a similar issue and managed to fix it by deleting "SportPaper/base/Paper/work/1.8.8/1.8.8-cl.jar"
> 
> What happened to me was that I initially ran the script on java 16, failed and moved to java 8, the previous attempt left an almost empty file rather than a 8.7mb file and that threw the ZipException.

Or just restart everything by cloning the repository again
