### ISSUE TITLE
Problem with bedwars plugin

### ISSUE THREAD

**Issue by lBoyka** [Electroid/SportPaper#105]
This happens when the server starts
I have been told that it may be registering the plugin separately

https://pastebin.com/XzmTm9vL

**Comment by andreasdc** [comment]
Probably broken plugin

**Comment by lBoyka** [comment]
The dev told me that it is a solution from sportpaper, other than that it works normally in paper or spigot

**Comment by andreasdc** [comment]
> The dev told me that it is a solution from sportpaper, other than that it works normally in paper or spigot

I really doubt it

**Comment by SoulzClub** [comment]
Idk, let's see if a sportpaper dev can tell me something

**Comment by lBoyka** [comment]
Idk let's see if a sportpaper dev can tell me something

**Comment by andreasdc** [comment]
I suggest going to plugin's dev or finding good developer, but you can wait for the answer here.

**Comment by PedroMPagani** [comment]
at com.axeelheaven.hbedwars.BedWars.onLoad(Unknown Source), its an error on the plugin, your dev is messing with NMS, sportpaper is a custom paper spigot, with different patches on NMS, etc.
Its the dev responsability to add support to it, it has nothing todo with sportpaper.

at com.axeelheaven.hbedwars.version.V1_8_R3.V1_8_R3.registerEntity(Unknown Source)
[14:34:49 WARN]:        at com.axeelheaven.hbedwars.version.V1_8_R3.V1_8_R3.<init>(Unknown Source)

**Comment by VytskaLT** [comment]
The plugin is trying to register a custom entity with ID 99. But there is already an entity with that ID, which is a Silverfish. Changing the ID to a bigger number should fix it.
