### ISSUE TITLE
how do I download the .jar to put it in the minecraft server?

### ISSUE THREAD

**Issue by MrRaffus** [Electroid/SportPaper#117]
hi I would like to know how to install the .jar in the server since there is no link to download I await answers thanks

**Comment by xIsm4** [comment]
> hi I would like to know how to install the .jar in the server since there is no link to download I await answers thanks

If you don't know how to, you can use my forked i built it.

**Comment by SrBlecaute01** [comment]
You can download [here](https://repo.ashcon.app/nexus/content/repositories/snapshots/app/ashcon/sportpaper/1.8.8-R0.1-SNAPSHOT/)
