### ISSUE TITLE
Nexus is down ?

### ISSUE THREAD

**Issue by theFoxley** [Electroid/SportPaper#120]
I can't build SportPaper and when i click on the nexus link i can't access it
https://repo.ashcon.app/nexus/content/repositories/releases/

**Comment by Pablete1234** [comment]
You can use this as an alternative repo for the time being: https://repo.pgm.fyi/#/snapshots/app/ashcon/sportpaper

**Comment by theFoxley** [comment]
Okay thanks !

**Comment by Electroid** [comment]
Yes, I will fix it this week.

**Comment by Electroid** [comment]
Should be restored!
