### ISSUE TITLE
World#setKeepSpawnInMemory(false) causes weird chunk loading issues

### ISSUE THREAD

**Issue by Electroid** [Electroid/SportPaper#13]
Chunks are sporadically loaded and cause rending issue for clients.

**Comment by cswhite2000** [comment]
When this method is run it attempts to unload all chunks that are in the spawn area, which could be causing these issues

**Comment by Electroid** [comment]
Yea, that would make sense, maybe it should just let them unload naturally.

**Comment by LinsaFTW** [comment]
Maybe you can try to remove patches 25 by 25 until fixed to know where the issue is coming from? I tried to do so but i have compilation failures :/

**Comment by MacacoLew** [comment]
Here is the fix
https://github.com/starlis/empirecraft/blob/master/patches/server/0063-Don-t-use-force-unload-for-keep-spawn-setting-change.patch

**Comment by VytskaLT** [comment]
Updated patch link: https://github.com/starlis/empirecraft/blob/master/patches/server/0062-Don-t-use-force-unload-for-keep-spawn-setting-change.patch
