### ISSUE TITLE
License

### ISSUE THREAD

**Issue by LoneDev6** [Electroid/SportPaper#18]
What is the license of this project? Same as Spigot?

**Comment by Electroid** [comment]
Should be same as Spigot, thanks for being this up, will make sure to clarify and add it.

**Comment by LoneDev6** [comment]
Thanks a lot!
Do you know if it's possible to fork this, extend its features and resell it?

**Comment by Adamaq01** [comment]
Hey, any news on adding that license ?

**Comment by Freebios** [comment]
Hey could this get merged into master :sunglasses: 
It would be great
