### ISSUE TITLE
tick loop bug

### ISSUE THREAD

**Issue by tomcraft** [Electroid/SportPaper#21]
Hey, I don't know if you know, but the latest 1.8 paper never fixed a bug they "implemented" with the tick loop.
A patch that fix this is available here: https://github.com/TacoSpigot/TacoSpigot/blob/version/1.8.8/PaperSpigot-Server-Patches/0023-Fix-tick-loop-bug.patch

Have a nice day :)

**Comment by Electroid** [comment]
Thanks, will take a look!

**Comment by sowhatifimlazy** [comment]
I've opened a pull request to bring this patch over to SportPaper.

**Comment by Electroid** [comment]
Thanks! Fixed in 96ddecc144563f06b073a0faa921496e06ed9fcf
