### ISSUE TITLE
Fix LuckPerms support

### ISSUE THREAD

**Issue by Lmmb74** [Electroid/SportPaper#28]
Hello. I just wanted to know about the progress regarding LuckPerms compatibility, as you said that it would be solved on this end.

**Comment by Lmmb74** [comment]
?

**Comment by seblawrence** [comment]
Please, in desperate need to use LuckPerms with Sport!

**Comment by Electroid** [comment]
Hi, the issue is known, and we'll fix it!

**Comment by Lmmb74** [comment]
Thanks :D
