### ISSUE TITLE
Incompatibility with Skript

### ISSUE THREAD

**Issue by dgo2001** [Electroid/SportPaper#30]
01.07 19:16:16 [Server] INFO [Skript] Enabling Skript v2.2-dev36
**614 | 01.07 19:16:17 [Server] ERROR [Skript] The Bukkit version 'Unknown-Version' does not contain a version number which is required for Skript to enable or disable certain features. Skript will still work, but you might get random errors if you use features that are not available in your version of Bukkit.**
615 | 01.07 19:16:17 [Server] ERROR Error occurred while enabling Skript v2.2-dev36 (Is it up to date?)
616 | 01.07 19:16:17 [Server] INFO java.lang.NoClassDefFoundError: org/bukkit/entity/WitherSkeleton
617 | 01.07 19:16:17 [Server] INFO at ch.njol.skript.entity.SimpleEntityData.(SimpleEntityData.java:204) ~[?:?]
618 | 01.07 19:16:17 [Server] INFO at ch.njol.skript.entity.EntityData.(EntityData.java:158) ~[?:?]
619 | 01.07 19:16:17 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_242]
620 | 01.07 19:16:17 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_242]
621 | 01.07 19:16:17 [Server] INFO at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108) ~[?:?]
622 | 01.07 19:16:17 [Server] INFO at ch.njol.skript.Skript.onEnable(Skript.java:372) ~[?:?]
623 | 01.07 19:16:17 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:320) ~[sportpaper.jar:git-SportPaper-"87b9752"]
624 | 01.07 19:16:17 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [sportpaper.jar:git-SportPaper-"87b9752"]
625 | 01.07 19:16:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:409) [sportpaper.jar:git-SportPaper-"87b9752"]
626 | 01.07 19:16:17 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:305) [sportpaper.jar:git-SportPaper-"87b9752"]
627 | 01.07 19:16:17 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:264) [sportpaper.jar:git-SportPaper-"87b9752"]
628 | 01.07 19:16:17 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:431) [sportpaper.jar:git-SportPaper-"87b9752"]
629 | 01.07 19:16:17 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:395) [sportpaper.jar:git-SportPaper-"87b9752"]
630 | 01.07 19:16:17 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:350) [sportpaper.jar:git-SportPaper-"87b9752"]
631 | 01.07 19:16:17 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [sportpaper.jar:git-SportPaper-"87b9752"]
632 | 01.07 19:16:17 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:667) [sportpaper.jar:git-SportPaper-"87b9752"]
633 | 01.07 19:16:17 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
634 | 01.07 19:16:17 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.WitherSkeleton
635 | 01.07 19:16:17 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[sportpaper.jar:git-SportPaper-"87b9752"]
636 | 01.07 19:16:17 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[sportpaper.jar:git-SportPaper-"87b9752"]
637 | 01.07 19:16:17 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
638 | 01.07 19:16:17 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
639 | 01.07 19:16:17 [Server] INFO ... 17 more
640 | 01.07 19:16:17 [Server] INFO [Skript] Disabling Skript v2.2-dev36

**Comment by AustinLMayes** [comment]
This was fixed in https://github.com/Electroid/SportPaper/commit/7af085b58f553264fab89b98a6f5494f490b14a9

Update to the latest release and try again.

**Comment by dgo2001** [comment]
Last version in https://pgm.dev/downloads/ still gives the same error. Furthermore, when i try to compile myself the last version this happens:
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Child module D:\User\Documentos\SportPaper\SportPaper-API\pom.xml of D:\User\Documentos\SportPaper\pom.xml does not exist @
[ERROR] Child module D:\User\Documentos\SportPaper\SportPaper-Server of D:\User\Documentos\SportPaper\pom.xml does not exist @
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project app.ashcon:sportpaper-parent:1.8-SNAPSHOT (D:\User\Documentos\SportPaper\pom.xml) has 2 errors
[ERROR]     Child module D:\User\Documentos\SportPaper\SportPaper-API\pom.xml of D:\User\Documentos\SportPaper\pom.xml does not exist
[ERROR]     Child module D:\User\Documentos\SportPaper\SportPaper-Server of D:\User\Documentos\SportPaper\pom.xml does not exist
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

**Comment by AustinLMayes** [comment]
@dgo2001 Keep in mind you need to run `./sportpaper build` to properly compile the project. 

The latest build can always be found [here](https://pkg.ashcon.app/sportpaper)
