### ISSUE TITLE
TNT no longer has a random velocity when ignited

### ISSUE THREAD

**Issue by mrcookieunderscore13** [Electroid/SportPaper#32]
In normal minecraft, when TNT is ignited, it has a small amount of random velocity. However, for some reason, TNT falls perfectly straight.

**Comment by Pugzy** [comment]
Same applies for dispenser TNT, no random so it breaks cannons that use it (like this one).

![image](https://user-images.githubusercontent.com/8608892/91635580-83738e80-e9f1-11ea-8c2f-c18b5df0b934.png)
_Resource pack used [diamyx-pack](https://github.com/Diamyx/diamyx-pack) available on Github._

**Comment by AustinLMayes** [comment]
This is not a bug. 

This happens if `fix-cannons` is set to `true` in the config.
