### ISSUE TITLE
Chunks not loading (Related to #13?)

### ISSUE THREAD

**Issue by LinsaFTW** [Electroid/SportPaper#39]
Hi, I have been trying to use SportPaper but there is an issue that causes worlds to not load properly.

This happens in worlds with the `keep spawn in memory = false` and if i turn off `keep-spawn-loaded` from `sportspigot.yml` it happens on the main world too.

**Comment by Electroid** [comment]
Yes, this is exactly related to #13. Not exactly sure what is going on, but this is a duplicate.
