### ISSUE TITLE
Chunk Memory Leak & CraftChatMessage-iteration

### ISSUE THREAD

**Issue by lordhadow1** [Electroid/SportPaper#40]
Does SportPaper fixes Chunk Memory Leak & CraftChatMessage-iteration like this fork: 

https://github.com/LinsaFTW/FlamePaper/blob/ver/1.8.8/Spigot-Server-Patches/0102-Fixed-memoryleak-limited-CraftChatMessage-iteration.patch

**Comment by MacacoLew** [comment]
No

**Comment by Electroid** [comment]
That link is a 404. If there is a patch, we're happy to accept it

**Comment by MacacoLew** [comment]
https://github.com/2LStudios-MC/FlamePaper/blob/ver/1.8.8/Spigot-Server-Patches/0102-Fixed-chunk-memory-leak.patch
https://github.com/2LStudios-MC/FlamePaper/blob/ver/1.8.8/Spigot-Server-Patches/0103-Limit-CraftChatMessage-iterations.patch
@Electroid
