### ISSUE TITLE
SportPaper doesn't like SkyWars plugin (?

### ISSUE THREAD

**Issue by MacacoLew** [Electroid/SportPaper#51]
I was testing with some SkyWars plugins like SkyWars Cookloco and HSkyWars, the same issue. Map not loading and this only happens with SportPapaer :eyes:

**Comment by MacacoLew** [comment]
![Uploading Captura de pantalla de 2021-01-19 13-50-51.png…]()

**Comment by AustinLMayes** [comment]
Please provide error logs and environmental information so we can help diagnose your issue.

**Comment by MacacoLew** [comment]
I was using HSkyWars first and the map was not loading when using SportPaper, i switched to PaperSpigot and everything works . Changed to SkyWars Cookloco (For testing) and using SportPaper is the same issue, Map not loading, im getting teleported to the void, theres no error logs and no useful info :roll_eyes:

**Comment by MacacoLew** [comment]
Fixed, was a issue of SportPaper and IDK HOW I FIXED THEM LOL
