### ISSUE TITLE
Gold Hearts broken?

### ISSUE THREAD

**Issue by MrMaikoX** [Electroid/SportPaper#56]
Gold Hearts doesn’t work with this spigot but works with other spigots. (Same client and same resource pack so I know it’s not my end)  no plugins are in the server either

https://gyazo.com/5defcdee27ebe1c4b71dd92775adce03

**Comment by VytskaLT** [comment]
Seems to be working for me

**Comment by linsaftw** [comment]
Works fine for me.

**Comment by Electroid** [comment]
We don't have enough information to debug, so going to close.
