### ISSUE TITLE
Optimize head rotation patch

### ISSUE THREAD

**Issue by RoccoDev** [Electroid/SportPaper#57]
[This patch](https://github.com/Electroid/SportPaper/blob/5ab471494b36601a9c04f2d55efdfde9cc2d5484/patches/server/0027-Fix-head-rotation-packet-spam.patch) is a good way to prevent broadcasting the packet in most cases (with frequent entity spawns like dropped items).

However, there's still a really unnecessary quadratic behavior, as the method that call belongs to is `updatePlayer`, which is already called once per tracked player, so we're broadcasting the packet to everyone *again* on each iteration.

Essentially the fix would be:
```patch
- this.broadcast(new PacketPlayOutEntityHeadRotation(this.tracker, (byte) i));
+ entityplayer.playerConnection.sendPacket(new PacketPlayOutEntityHeadRotation(this.tracker, (byte) i));
```
Moreover, this has already been changed on upstream Spigot: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/nms-patches/EntityTrackerEntry.patch#157

**Comment by TheDGOfficial** [comment]
Maybe open a PR? You've already provided the suggested change. I'd like to see this implemented as well.

**Comment by Electroid** [comment]
That would be great! ^ Patch is welcome
