### ISSUE TITLE
Suspending the Server and TPS

### ISSUE THREAD

**Issue by arttwart** [Electroid/SportPaper#62]
When I leave the server, it says that: https://srcb.in/qtNtpVTU9g What is this?
My version: CraftBukkit version git-SportPaper-v1.0-11-g8226346 (MC: 1.8.8) (Implementi
ng API version 1.8.8-R0.1-SNAPSHOT)

Also my TPS was 20* with Paper 1.8.8, but sometimes it goes down. I couldn't understand what is the problem.

**Comment by arttwart** [comment]
![image](https://user-images.githubusercontent.com/76517247/112717779-ca7e1f80-8eff-11eb-95e4-ab1c37ab48ad.png)

**Comment by VytskaLT** [comment]
I might be wrong, but the suspend just saves resources when the server is inactive

**Comment by arttwart** [comment]
> I might be wrong, but the suspend just saves resources when the server is inactive

Did you mean "Stopped" or "No one in server"? Because server was not stopped.

**Comment by VytskaLT** [comment]
> > I might be wrong, but the suspend just saves resources when the server is inactive
> 
> Did you mean "Stopped" or "No one in server"? Because server was not stopped.

I mean when there is no one in the server, it "suspends" it by probably unloading the spawn chunks and more stuff to use less resources

**Comment by Electroid** [comment]
That's correct. You can disable suspending (if you want) by changing the suspend duration in the `sportpaper.yml` to a really long duration (like weeks or a year)
