### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by arttwart** [Electroid/SportPaper#64]
Normally Paper has cache files. Why Sport Paper hasn't?

**Comment by TheDGOfficial** [comment]
I'm assuming you are talking about the `cache` folder. That folder is generated by Paperclip and contains vanilla and patched (paper) server JARs, to avoid re-downloading/patching them on every start-up. If hashes of them match, Paperclip uses them. SportPaper does not use Paperclip and directly provides the patched JAR, so there is no need for it.

**Comment by arttwart** [comment]
> I'm assuming you are talking about the `cache` folder. That folder is generated by Paperclip and contains vanilla and patched (paper) server JARs, to avoid re-downloading/patching them on every start-up. If hashes of them match, Paperclip uses them. SportPaper does not use Paperclip and directly provides the patched JAR, so there is no need for it.

Understood, thanks.
