### ISSUE TITLE
Plugin Disabling Itself

### ISSUE THREAD

**Issue by arttwart** [Electroid/SportPaper#65]
[Holographic Placeholders](https://www.spigotmc.org/resources/holographic-placeholders.64535/) plugin disabling itself with Sport Paper. I contacted to developer of the plugin and he said: **"Your fork of Spigot apparently doesnt have all the functions, my plugin is only supported on Spigot and original Paper. Not forks of them."**
org.bukkit.craftbukkit.v1_8_R3.CraftServer.getOfflinePlayers

**Error:** https://sourceb.in/E3Kox7JUVZ

Is that means, I won't be able to use it forever or are you going to fix this?

**Comment by cswhite2000** [comment]
SportPaper does not modify the getOfflinePlayer method in CraftServer. So the error you're running into is not SportPaper specific. In this instance however it looks like your `playerdata` directory in the `world` folder is empty which is what seems to be causing the NullPointerError.
