### ISSUE TITLE
COMPILE ERROR

### ISSUE THREAD

**Issue by uRyanxD** [Electroid/SportPaper#68]
Hello, well, I'm having an error with something related to patches when compiling, is there a link that I could download a jar directly?

**Comment by TheDGOfficial** [comment]
Which errors you are getting, so we can solve them? Anyway, the pre-built JAR can be found here:
https://repo.ashcon.app/nexus/content/repositories/snapshots/app/ashcon/sportpaper/1.8.8-R0.1-SNAPSHOT/sportpaper-1.8.8-R0.1-20210417.174049-36.jar (build 36)

For latest build, you have to open https://repo.ashcon.app/nexus/content/repositories/snapshots/app/ashcon/sportpaper/1.8.8-R0.1-SNAPSHOT/ and scroll to bottom, and click on the jar with highest build number and ending with .jar (not .jar.md5 or such)

Don't know Nexus much so if there is a pre-built route to download latest version directly, someone correct me.

**Comment by VytskaLT** [comment]
If you are on Windows, you'll have to use WSL for compiling SportPaper.

**Comment by uRyanxD** [comment]
Yes, I am using Windows. Thank you for your help!
