### ISSUE TITLE
Problem with Skinsrestorer

### ISSUE THREAD

**Issue by lBoyka** [Electroid/SportPaper#82]
Hi, I have a question because when I use skinsrestorer on my server running Sportpaper the hotbar disappears when I enter, well I do not know if it is exactly a problem of sportpaper or PGM. Since it does not happen to me in the servers that I use paper.

I also when I use the skinsrestorer in the sportpaper with bungeecord=true in its sportpaper.yml, I get all its folders.

I mean on the paper side when I run skinsrestorer with bungeecord=true , I only get its folder that says "Use bungee config for settings!", to only make changes in the config.yml on the bungee side, but on the sportpaper I get all its folders, why does that happen?
It should be the same as when I run it in paper or spigot.

**Comment by RoccoDev** [comment]
Could you record when this happens? Do you have any plugins that may be setting the player's game mode to spectator?

Barring client glitches, I don't currently know a way to make the hotbar disappear without spectator mode.

On the other hand, I believe the client sets client-side spectator mode if it receives that info from the player info packet, which I assume both SR and SportPaper are modifying.
