### ISSUE TITLE
Explosion knockback can get you kicked

### ISSUE THREAD

**Issue by Pablete1234** [Electroid/SportPaper#83]
In the current latest upstream sportpaper, building certain tnt contraptions that result in high player velocities can get them kicked for trying to send invalid movement packets (when the client responds to the server they get themselves kicked).

I  think it's related to https://github.com/Electroid/SportPaper/commit/0dc4407c7d41a7c091b41b56e0366a4e90581b10 but i cannot tell for sure

**Comment by VytskaLT** [comment]
Yep, I'm having the same issue, before that patch it never happened to me, so it must be an issue with it. Pretty sure this is the line that causes it: https://github.com/Electroid/SportPaper/commit/0dc4407c7d41a7c091b41b56e0366a4e90581b10#diff-440b8239542a35b5ad543b7a2df53b3330f7aa2f3d722106f653472cb329ad05R105
