### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by tommasobenatti** [Electroid/SportPaper#84]
Hi, I was just compiling the latest commit (18f33e3) and I'm getting this error while running `./sportpaper build`
https://paste.tommasobenatti.dev/mihumotula.sql
I'm compiling with Java 8

**Comment by VytskaLT** [comment]
I'm not sure why you're getting that error, but you can get the latest jar here: https://repo.ashcon.app/nexus/content/repositories/snapshots/app/ashcon/sportpaper/1.8.8-R0.1-SNAPSHOT/sportpaper-1.8.8-R0.1-20210502.193134-39.jar

**Comment by tommasobenatti** [comment]
Ok, thanks i'll close the issue

**Comment by para-dise** [comment]
Well, uh, an actual fix aside from closing this would be nice

**Comment by VytskaLT** [comment]
If you're on Windows, try to use WSL, that fixed all compiling issues for me.
