### ISSUE TITLE
Cannot compile jar

### ISSUE THREAD

**Issue by sasi2006166** [Electroid/SportPaper#88]
See other comment.

**Comment by sasi2006166** [comment]
Apparently i got it working, but as always, won't compile at the end.

https://pastebin.com/EDCt7yge

**Comment by VytskaLT** [comment]
Try to do `mvn clean install` yourself.

**Comment by egorsgn** [comment]
> Try to do `mvn clean install` yourself.

Didn't help, what to do? I have the same problem, please help

**Comment by sasi2006166** [comment]
So? Where is support?

**Comment by AustinLMayes** [comment]
Fixed in https://github.com/Electroid/SportPaper/commit/86c63dd5ba830b07417cf868b388d026cd9aebbf and https://github.com/Electroid/SportPaper/commit/b72a19be6ca0f50f94d267b46abc989db2be86ff

**Comment by cstles** [comment]
> Fixed in [86c63dd](https://github.com/Electroid/SportPaper/commit/86c63dd5ba830b07417cf868b388d026cd9aebbf) and [b72a19b](https://github.com/Electroid/SportPaper/commit/b72a19be6ca0f50f94d267b46abc989db2be86ff)

Cap
