### ISSUE TITLE
Fix teleport invisibility

### ISSUE THREAD

**Issue by andreasdc** [Electroid/SportPaper#92]
causes some players to be hidden for you when you are switching servers

**Comment by Electroid** [comment]
Fixed by 18f33e3a30084a206345ece760df27c4f04da571

**Comment by andreasdc** [comment]
> Fixed by [18f33e3](https://github.com/Electroid/SportPaper/commit/18f33e3a30084a206345ece760df27c4f04da571)

It was caused by something different, but I will use this patch too. Do you know situations when this patch will help?
