### ISSUE TITLE
Disable server suspension

### ISSUE THREAD

**Issue by timof121** [Electroid/SportPaper#93]
Hello, i have the same problem as issue #62. Ive seen that the solution is to set the suspention time to 1Yer or something like that. But how do i do that? When in the config i set the time to PT1Y or PT9999M the console spams with errors that say its invalid
![Screenshot_20210712-103950](https://user-images.githubusercontent.com/52547763/125257266-87548a80-e2fd-11eb-9455-fcc81dc1a0ca.png)
So how do i set the suspension time to *infinite*?

**Comment by AustinLMayes** [comment]
A year would be `P1Y`. 

See [this page](https://www.digi.com/resources/documentation/digidocs/90001437-13/reference/r_iso_8601_duration_format.htm) for reference.
