### ISSUE TITLE
Badly Compressed Packet - Need help SA

### ISSUE THREAD

**Issue by yiatzz** [Electroid/SportPaper#99]
Hi. Recently i started to have some issues with SportPaper, whenever i teleport to a location (chunk) that has a construction, like the server's spawn i get disconnected saying that the packet was badly compressed.

![image](https://user-images.githubusercontent.com/47675544/131189015-c14a8656-8c35-4221-a0fa-813c9c506262.png)

Server behind a Velocity 3.0.0 Proxy
Centos7

**Comment by VytskaLT** [comment]
did you try not using a proxy?

**Comment by yiatzz** [comment]
> did you try not using a proxy?

I didnt but soon as i get home i'll

**Comment by yiatzz** [comment]
> did you try not using a proxy?

same, tested localhost

 Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 2215833 into 3

**Comment by yiatzz** [comment]
with vanilla paper it work just fine idk,

i've set network-compression-threshold to -1, 256 and 512 all the same ;(

**Comment by yiatzz** [comment]
imo Packet is PacketPlayMapOutChunk and the above excpetion is on PacketDecompressor 
![image](https://user-images.githubusercontent.com/47675544/131230236-0022eafb-4777-49f8-ae58-8830064ed010.png)

**Comment by yiatzz** [comment]
> imo Packet is PacketPlayMapOutChunk and the above excpetion is on PacketDecompressor
> ![image](https://user-images.githubusercontent.com/47675544/131230236-0022eafb-4777-49f8-ae58-8830064ed010.png)

this ofc is when i have compression turned on, when i deactivate it (-1) it prints the Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 2215833 into 3 exception

**Comment by VytskaLT** [comment]
I'm not home right now, so I can't check this on my own, but it's then probably an issue with PacketPlayMapOutChunk. You can try to check what SportPaper patches change the map chunk packet class maybe.

**Comment by yiatzz** [comment]
> I'm not home right now, so I can't check this on my own, but it's then probably an issue with PacketPlayMapOutChunk. You can try to check what SportPaper patches change the map chunk packet class maybe.

i didnt find none
![image](https://user-images.githubusercontent.com/47675544/131231292-66b0c883-5c1d-4f80-8c8e-d51d3f8144ee.png)

**Comment by yiatzz** [comment]
maybe we can try to debug the packet with vanilla paper and with sportpaper but idk how to do that
it maybe a entity or block or a nbt tag idk i just need help :(

**Comment by yiatzz** [comment]
i trully believe that this is the packet that's crashing 

![image](https://user-images.githubusercontent.com/47675544/131233629-910e15d4-8f34-4b32-8b16-32a1f44125ae.png)

**Comment by yiatzz** [comment]
https://www.mediafire.com/file/qn4uw56xq6obcu7/2021-08-28_2.json/file that's a json logged packets from when i crashed.

**Comment by RedeObscurity** [comment]
https://www.spigotmc.org/threads/badly-compressed-packet-1-8-clients.28815/
